### ISSUE TITLE
Custom attribute for option tag

### ISSUE THREAD

**Issue by uyab** [spatie/laravel-html#104]
I need to generate option tag with custom attribute, e.g. `<option value=1 data-parent=8>Jakarta</option>`. Is it possible to do that using `html()->select()` helper?

**Comment by sebastiandedeyne** [comment]
It's possible, but you'll need to add the options yourself instead of using the helper function.

Here's what the implementation looks like:

https://github.com/spatie/laravel-html/blob/32ae895f65f89d474430ef1fe4b6c54f65327938/src/Elements/Select.php#L51-L68

So something like this should do the trick:

```php

$countries = $countries->map(function ($country) {
    return html()
        ->option($country->name, $country->id)
        ->attribute('data-parent', $parent);
});

html()->select('contry')
    ->children($countries)
    ->value(old('country'));
```

**Comment by iosiflivadaru** [comment]
How to give attributes to options that are inside a select tag?

I'm not sure how am I supposed to use this -> https://docs.spatie.be/laravel-html/v2/general-usage/element-classes/#option  .

For example I want to make one option selected if it matches whatever the condition is.
