### ISSUE TITLE
Form method()

### ISSUE THREAD

**Issue by rickselby** [spatie/laravel-html#34]
Calling `html()->form('PUT')` and `html()->form()->method('PUT')` generates different HTML - the latter does not add the `_method` child.

I was thinking of overriding the `open` method in `Spatie\Html\Elements\Form` and checking if the `_method` and `token` children are required there; would that be an acceptable way of solving this issue? I'm happy to put in a PR but would like to do it the 'right' way.

**Comment by sebastiandedeyne** [comment]
This is intentional. One thing I wanted to ensure when writing this package, is that sometime you want to build HTML without any context-specific magic. All the "extra's", like csrf and _method fields, are only generated when using the actual builder. If you're using element classes by themselves, or element class instances returned from the builder, there's no hand-holding involved anymore.

This is also described under concepts in the readme:

https://github.com/spatie/laravel-html#concepts

**Comment by rickselby** [comment]
That makes sense, thanks for the clarification.
