### ISSUE TITLE
Form Model and Multi-Select Support?

### ISSUE THREAD

**Issue by paulredmond** [spatie/laravel-html#7]
I have a couple questions about multi-select (`<select multiple=true/>`). I am not opposed to looking at doing a PR, but I wanted to check in and ask a few questions.

1. Can a model form work with model associations? Is this planned?
1. If not implemented yet, would you suggest something other than the following for multi-select `<select>` elements?
```blade
<select name="roles[]" class="form-control select2" multiple>
    @foreach($roles as $value => $role)
    {{ html()
        ->option($role, $value)
        ->selectedIf(in_array($value, $user->roles->pluck('id')->toArray()))
    }}
    @endforeach
</select>
```

I am using the https://github.com/spatie/laravel-permission package for roles, but just curious about any model in general.

**Comment by freekmurze** [comment]
The code you provided seems like the way to go.

@sebastiandedeyne your thoughts on this?

**Comment by sebastiandedeyne** [comment]
This could be better. A `multiselect` method on `Html` would be nice, which would accept an array of values (you can't pass an array to `select` since it has a `?string` typehint)

**Comment by danijelk** [comment]
I would also point you in a direction towards adding a dynamic ->attach(iterable $options = []). We noticed that 'multiple' is impossible to add it seems, but then comes other attributes as well such as the dynamic data-attrib*, so adding this attacher would pave the road to a great deal of more usage for this package than to add really really basic html attributes (in a nifty way).

**Comment by danijelk** [comment]
Any plans for this? Would be nice to make the switch, but without having to do too many rewrites

**Comment by bbashy** [comment]
@danijelk There's probably plans but best to submit it yourself via PR if you need it?

**Comment by paulredmond** [comment]
@danijelk The code I provided originally should be easy to refactor if and when a multiple method gets implemented 👍

**Comment by danijelk** [comment]
@paulredmond indeed, we're mostly interested in the ability to add attributes to start with, and see how far we can go. @bbashy want to be 99% sure they would be ok with this idea before spending some time on the PR :)

**Comment by sebastiandedeyne** [comment]
I definitely want to see this feature added to the package, haven't had time to do it myself. A PR would be welcome, I'll most likely pull this in (unless it adds a bunch of inconsistencies and voodoo magic somehow though 😄)

**Comment by paulredmond** [comment]
@sebastiandedeyne PR for `Html::multiselect()` in the works, expect it soon 👍

**Comment by sebastiandedeyne** [comment]
Hey all,

I've decided to pull in @Propaganistas's PR since that's my preferred implementation.

Since the necessary typehint change is breaking, I'm going to release a v2 soon. Don't worry, upgrading to v2 will most likely be nothing more than a simple dependency change and `composer update`. I'll write up a detailed upgrade guide stating why a major version was needed, and in which cases you'll need to modify your code (which is only if you're extending the class and modifying implementations). The new version will reduce the amount of typehints in this package, since they're more of a hassle than a convenience in this case.

If you want `Select::multiple` today, you can require a specific commit with composer: `dev-master#3ece2b92a03bf7c64574fc33d6f2421a760be67d`. I'll probably be releasing v2 somewhere at the end of this month.

Meanwhile, big thanks to both @paulredmond and @Propaganistas for their PR's and all the rest for your input on this issue!

**Comment by sebastiandedeyne** [comment]
Version 2 is out already so you can require a stable version for this!
